### ISSUE TITLE
[feature request] lint rules: add `@typescript-eslint/eslint-plugin-tslint`

### ISSUE THREAD

**Issue by DerekNonGeneric** [OpenINF/openinf-util-object#191]
This dependency should be removed; we want to have errors and warnings to differentiate severity/provide guidance on what to do.

_Originally posted by @DerekNonGeneric in https://github.com/openinf/util-object/pull/189#pullrequestreview-1203606883_

**Comment by DerekNonGeneric** [comment]
I would also like to include [`@typescript-eslint/eslint-plugin-tslint`](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin-tslint) and see about adding some rules from https://github.com/openinf/tslint-microsoft-contrib (amongst others TSLint-specific ones).

**Comment by sumitshinde-84** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by DerekNonGeneric** [comment]
Sure, @sumitshinde-84; i just updated to the latest versions of ESLint and pnpm, so you should be good to go at this point.

**Comment by DerekNonGeneric** [comment]
okay, great; we need to figure out what specific rules of theirs we like&hellip;

any suggestions you make along the way would be appreciated.

**Comment by DerekNonGeneric** [comment]
unmet peer:

![image](https://github.com/OpenINF/openinf-util-object/assets/17770407/72a6b3d4-216b-44df-a872-d91f8a741c3a)

**Comment by sumitshinde-84** [comment]
No inputs were found in config file '/home/sumit/Desktop/openinf-util-object/tsconfig.json'. Specified 'include' paths were '["src/**/*.ts"]' and 'exclude' paths were '[]'.ts           got these error

**Comment by sumitshinde-84** [comment]
getting this error - 
No inputs were found in config file '/home/sumit/Desktop/openinf-util-object/tsconfig.json'. Specified 'include' paths were '["src/**/*.ts"]' and 'exclude' paths were '[]'.ts

**Comment by DerekNonGeneric** [comment]
> Specified 'include' paths were '["src/**/*.ts"]' and 'exclude' paths were '[]'.ts

Pretty sure one would need to make that be '["**/src/**/*.ts"]'

**Comment by sumitshinde-84** [comment]
@DerekNonGeneric  I've tried multiple variations of the file inclusion pattern, including "./packages/object-util/src/**/*.ts", "packages/object-util/src/**/*.ts", and "**/src/**/*.ts", but unfortunately, none of them have resolved the issue. It seems that we need to reevaluate our ESLint and TypeScript ESLint configurations to address this problem.

**Comment by sumitshinde-84** [comment]
I've tried multiple variations of the file inclusion pattern, including "./packages/object-util/src/**/*.ts", "packages/object-util/src/**/*.ts", and "**/src/**/*.ts", but unfortunately, none of them have resolved the issue. It seems that we need to reevaluate our ESLint and TypeScript ESLint configurations to address this problem.

**Comment by sumitshinde-84** [comment]
I've tried multiple variations of the file inclusion pattern, including ["./packages/object-util/src/**/*.ts"], ["packages/object-util/src/**/*.ts"], and ["**/src/**/*.ts"], but unfortunately, none of them have resolved the issue. It seems that we need to reevaluate our ESLint and TypeScript ESLint configurations to address this problem.

**Comment by sumitshinde-84** [comment]
I've tried multiple variations of the file inclusion pattern, including ```"./packages/object-util/src/**/*.ts"```, "packages/object-util/src/**/*.ts", and "**/src/**/*.ts", but unfortunately, none of them have resolved the issue. It seems that we need to reevaluate our ESLint and TypeScript ESLint configurations to address this problem.

**Comment by sumitshinde-84** [comment]
I've tried multiple variations of the file inclusion pattern, including ```"./packages/object-util/src/**/*.ts"```, ```"packages/object-util/src/**/*.ts"```, and ```"**/src/**/*.ts"```, but unfortunately, none of them have resolved the issue. It seems that we need to reevaluate our ESLint and TypeScript ESLint configurations to address this problem.

**Comment by DerekNonGeneric** [comment]
`tsconfig.eslint.json`:

```json
{
  "extends": "./tsconfig.base.json",
  "include": ["packages/**/*.ts", "tools/**/*.ts", ".eslintrc.js"]
}
```

**Comment by DerekNonGeneric** [comment]
Alright, well done @sumitshinde-84. That will need to be taken care of over there (if necessary).

I went ahead and opened an issue in that fork of ours that we made; am closing this out now!

https://github.com/OpenINF/openinf-tslint-microsoft-contrib/issues/2
